import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/theme-provider';
import { HydrationOverlay } from '@builder.io/react-hydration-overlay';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeModeToggle } from '@/components/ThemeBtn';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HydrationOverlay>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Theme toggle positioned at top-right */}
            <div className="absolute right-4 top-4 z-50">
              <ThemeModeToggle />
            </div>

            {children}
          </ThemeProvider>
        </HydrationOverlay>
      </body>
    </html>
  );
}
